from domain.exceptions.domain_exception import DomainException


class DomainEntityException(DomainException):
    pass
