from shared.basic_exception import CustomException


class APICustomException(CustomException):
    pass
