from shared.basic_exception import CustomException


class APIException(CustomException):
    pass
